### ISSUE TITLE
4Mhz Fuse Values

### ISSUE THREAD

**Issue by C4** [ambasat/AmbaSat-1#2]
Hi, I was wondering what fuse values you were using to for the Atmega32P-AU chips before you install them on the boards? This would be nice to know for others that are building ambasat boards. Thanks!

**Comment by ambasat** [comment]
Hi, here are the fuse values for 1MHz:

ambasatnode.menu.mhz.1MHz.bootloader.low_fuses=0x62
ambasatnode.bootloader.high_fuses=0xD6
ambasatnode.bootloader.extended_fuses=0x06
 
For 4MHz, change:

ambasatnode.menu.mhz.4MHz.bootloader.low_fuses=0x7D
