### ISSUE TITLE
Schematic in pdf or similar

### ISSUE THREAD

**Issue by mfalkvidd** [ambasat/AmbaSat-1#3]
Could someone add a pdf or similar of the schematic, for people who want to view the schematic but don't want to install Eagle?

**Comment by UliSchirm** [comment]
Very good idea! I would also appreciate if someone could provide a PDF schematic.

**Comment by ambasat** [comment]
PDF version of the AmbaSat-1 mainboard now added:
https://github.com/ambasat/AmbaSat-1/tree/master/Release/Eagle/Motherboard
